### ISSUE TITLE
MIT LICENSE UPDATE

### ISSUE THREAD

**Issue by jasonetorres** [prakhartiwari0/my-web-shortcuts#11]
---
name: MIT LICENSE UPDATE
about: add contact information to LICENSE 
---

**Describe the bug**
would be a good addition to add:
**Contact Information:**
For questions or inquiries related to this license, please contact Prakhar Tiwari at @Prakhartiwari0

**Expected behavior**
will make it so anyone reviewing doc can ask questions if need be

---

**Comment by prakhartiwari0** [comment]
The contact details are not required to be given inside the license file. It exists in CONTRIBUTING.md for any query related to the project. Or anybody can simply contact me on any social accounts listed on my GitHub profile, so this is not required.
I hope I was able to explain :smile: 

Happy Contributing!
