### ISSUE TITLE
[BUG] Missing icons + GitHub glitch

### ISSUE THREAD

**Issue by beingsie** [prakhartiwari0/my-web-shortcuts#37]
## Bug: Icons not loading
- Also I have found a weird bug that is occurring with the icons not loading."

### Screenshot of bug:
<img width="970" alt="image" src="https://github.com/prakhartiwari0/my-web-shortcuts/assets/140430987/437d1e64-d3e9-4a91-87a0-05d6ab968018">

### Further issues:
- This is also causing a weird glitch on GitHub, as you can see from the screenshot, every time I open the extension, the icons go missing for GitHub as well.

### Testing:
- I have tested the recent update on Chrome, Firefox and Opera which all return the same bug.

### Notes:
- I have the recent changes synced correctly. The issue with the GitHub glitch goes away on refreshing the page but returns as soon as I open the extension.

**Comment by prakhartiwari0** [comment]
Are the icons missing on every other website?

**Comment by prakhartiwari0** [comment]
Okay I have got the solution, will make a PR to solve this :)
Thanks for pointing it out! @beingsie

**Comment by prakhartiwari0** [comment]
This commit should solve the issue: https://github.com/prakhartiwari0/my-web-shortcuts/commit/7fe866b79214be6efe2c54b85c3ec6997e582f08

Please confirm @beingsie

**Comment by beingsie** [comment]
> This commit should solve the issue: [7fe866b](https://github.com/prakhartiwari0/my-web-shortcuts/commit/7fe866b79214be6efe2c54b85c3ec6997e582f08)
> 
> Please confirm @beingsie, can you check that again? Remove the extension and install the latest version.

Great! This commit fixes the issue, good fix!
