### ISSUE TITLE
grammatical error in the README file.

### ISSUE THREAD

**Issue by jasonetorres** [prakhartiwari0/my-web-shortcuts#5]
Upon reviewing the project documentation, I noted there was a missing period at the end of the readme file. I went through each doc and noted that was the only issue I found. 
<img width="840" alt="Screenshot 2023-10-13 at 5 51 38 AM" src="https://github.com/prakhartiwari0/my-web-shortcuts/assets/110337114/09d8994d-1765-4b0a-ac99-eb2f703cecab">

**Comment by prakhartiwari0** [comment]
Good one @jasonetorres, if you can, then please try and find more such errors. I bet there will be a lot of them because I wrote the docs without any auto-correction :joy:

**Comment by jasonetorres** [comment]
I think it's done I may have not done the PR correct
