### ISSUE TITLE
[feat] Add PR Template for Consistency

### ISSUE THREAD

**Issue by shubhsharma19** [prakhartiwari0/my-web-shortcuts#6]
## Description

A PR template will ensure that everyone follows a certain way to create, describe the changes while opening a PR.

**Comment by jasonetorres** [comment]
if you aren't taking this i would like to do it.


I already have a template setup.

**Comment by shubhsharma19** [comment]
> if you aren't taking this i would like to do it.
> 
> I already have a template setup.

I actually created a PR for this you can create an issue for issue templates addition next :D
