### ISSUE TITLE
Add Issue Template for Consistency

### ISSUE THREAD

**Issue by jasonetorres** [prakhartiwari0/my-web-shortcuts#9]
ISSUE_TEMPLATE.md

---
name: Bug Report
about: Create a report to help us improve
---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g., Windows 10]
 - Browser: [e.g., Chrome, Firefox]
 - Version: [e.g., 22]

**Additional context**

---

**Note to the Issue Creator**

Please make sure your issue follows these guidelines:
- Check if a similar issue has already been reported.
- Use a clear and descriptive title for your issue.
- Specify the steps to reproduce the issue.
- Provide as much detail as possible, including screenshots, error messages, and your environment.
- Be respectful and considerate in your descriptions and comments.

---

**Issue Checklist**

- [ ] I have checked for similar issues before creating this one.
- [ ] My issue title is clear and descriptive.
- [ ] I have provided clear steps to reproduce the issue.
- [ ] I have included all relevant details, such as screenshots and environment information.

**Comment by prakhartiwari0** [comment]
Issue templates have been created.
